allowBuilds:
  '@firebase/util': set this to true or false
  core-js: true
  msw: true
  protobufjs: set this to true or false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - posthog-js@1.404.1
