allowBuilds:
  core-js: set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
onlyBuiltDependencies:
  - msw
  - sharp
  - unrs-resolver
  - "@firebase/util"
  - protobufjs
overrides:
  hono: "4.12.25"
